- name: enable rh-php72
  copy:
    dest: /etc/profile.d/enable-rhphp72.sh
    content: |
      #!/bin/bash
      source scl_source enable rh-php72
    mode: 0644

- name: load rh-php72 script
  shell: source /etc/profile.d/enable-rhphp72.sh

- name: Restart rh-php72-php-fpm
  systemd:
    name: rh-php72-php-fpm
    state: restarted