---

- name: Set SELinux to Permissive
  selinux:
    policy: targeted
    state: permissive

- name: Install Epel Repository
  yum:
    name: epel-release
    state: installed

- name: Install Nginx
  yum:
    name: nginx
    state: installed

- name: Enable and Start Nginx
  systemd:
    name: nginx
    enabled: yes
    state: started

