---

- name: Set SELinux to Permissive
  selinux:
    policy: targeted
    state: permissive

- name: Install Software Collections
  yum:
    name: centos-release-scl
    state: installed

- name: Install Epel Repository
  yum:
    name: epel-release
    state: installed

- name: Install Nginx
  yum:
    name: nginx
    state: installed

- name: Enable and Start Nginx
  systemd:
    name: nginx
    enabled: yes
    state: started

- name: Install PHP 7.2 and modules
  yum:
    name: >
      rh-php72, rh-php72-php-fpm, rh-php72-php-gd, rh-php72-php-json,
      rh-php72-php-mbstring, rh-php72-php-mysqlnd,
      rh-php72-php-xml, rh-php72-php-xmlrpc, rh-php72-php-opcache
    state: installed
  notify:
    - enable rh-php72
    - load rh-php72 script

  notify:
    - enable rh-php72

- name: Install MariaDB 10.2
  yum:
    name: rh-mariadb102
    state: installed
  notify:
    - enable rh-mariadb102
    - load rh-mariadb102 script

- name: Enable MariaDB service
  systemd:
    name: rh-mariadb102-mariadb
    state: started
    enabled: yes

- name: Enable PHP 7.2 FPM
  systemd:
    name: rh-php72-php-fpm
    state: started
    enabled: yes

